// frontend-v/src/components/Grid.vue
<script>
import { getProgItem } from './BaseHelper';

export default {
    props: [ 'progId', 'dataSource', 'config' ],
    setup(props) {
    },
    data() {
        return {
            pageProg : null
        }
    },
    methods: {
    },
    created() {
        this.pageProg = getProgItem(this.progId);
        if (null == this.pageProg) {
            alert('Please close this page, grid load fail!');
            window.location = "/";
        }        
    },
    mounted() {
    } /* ,
    watch : {
        dataSource : {
            deep : true,
            handler() {
                console.log('array updated');
            }
        }
    } */
}
</script>

<template>
<div class="col-xs-12 col-md-12 col-lg-12">
    <table class="table table-hover table-bordered" v-if="this.dataSource != null && this.dataSource.length > 0">
        <thead>
            <tr>
                <th v-for="col in config.column" v-bind:style="'background-color:' + config.theadColor.backgroundColor + '; color:' + config.theadColor.color + ';'">{{col.label}}</th>
            </tr>            
        </thead>
        <tbody>
            <tr v-for="row in dataSource">
                <td v-for="col in config.column">
                    <template v-if="config.keyFieldFormatter.field == col.field">
                        <template v-for="keyFieldFormatItem in config.keyFieldFormatter.item">
                            <template v-if="   typeof keyFieldFormatItem.method === 'function'  ">
                                <button v-if="  config.keyFieldFormatter.showTooltip " v-bind:id="'_' + keyFieldFormatItem.type + '_' + row[col.field]" v-bind:class="keyFieldFormatItem.class" @click="keyFieldFormatItem.method(row[col.field])" data-bs-toggle="tooltip" data-bs-placement="bottom" v-bind:data-bs-title="keyFieldFormatItem.memo" data-trigger="hover"><i v-bind:class="'bi bi-' + keyFieldFormatItem.icon "></i></button>
                                <button v-if=" !config.keyFieldFormatter.showTooltip " v-bind:id="'_' + keyFieldFormatItem.type + '_' + row[col.field]" v-bind:class="keyFieldFormatItem.class" @click="keyFieldFormatItem.method(row[col.field])"><i v-bind:class="'bi bi-' + keyFieldFormatItem.icon "></i></button>
                                &nbsp;
                            </template>
                            <template v-if=" !(typeof keyFieldFormatItem.method === 'function') ">{{row[col.field]}}</template>
                        </template>
                    </template>
                    <template v-if="config.keyFieldFormatter.field != col.field">{{row[col.field]}}</template>
                </td>
            </tr>
        </tbody>
    </table>
</div>
</template>

// frontend-k/src/components/Grid.svelte
<script>
import { Table, Button, Icon, Tooltip } from "sveltestrap";

export let config = {};
export let dataSource = [];

</script>
<script context="module">
export function getGridConfig(keyFieldName, formatterItems, columnItems) {
    var gridConfig = {
        row : 10,
        page : 1,
        total : 0,
        theadColor : {
            'backgroundColor' : '#575757',
            'color'           : 'whitesmoke'
        },
        keyFieldFormatter : {
            'field' : (null == keyFieldName || '' == keyFieldName) ? 'oid' : keyFieldName,
            'showTooltip' : false,
            'item' : formatterItems
        },
        column : columnItems
    };
    return gridConfig;
}
export function setConfigRow(gridConfig, row) {
    gridConfig.row = row;
}
export function setConfigPage(gridConfig, page) {
    gridConfig.page = page;
}
export function setConfigTotal(gridConfig, total) {
    gridConfig.total = total;
}
</script>
<div class="col-xs-12 col-md-12 col-lg-12">
    
    {#if null != dataSource && dataSource.length > 0 }
    <Table bordered hover>
        <thead>
        <tr>
            {#each config.column as col}
            <th style="background-color:{config.theadColor.backgroundColor}; color:{config.theadColor.color};">{col.label}</th>
            {/each}
        </tr>
        </thead>
        <tbody>
            {#each dataSource as row}
            <tr>
                {#each config.column as col}
                    {#if config.keyFieldFormatter.field == col.field}
                        <td>
                        {#each config.keyFieldFormatter.item as keyFieldFormatItem}                            
                            {#if typeof keyFieldFormatItem.method === 'function' }
                                {#if config.keyFieldFormatter.showTooltip }
                                <Button id={'_' + keyFieldFormatItem.type + '_' + row[col.field]} class={keyFieldFormatItem.class} on:click={keyFieldFormatItem.method(row[col.field])}><Icon name={keyFieldFormatItem.icon}></Icon></Button>
                                <Tooltip target={'_' + keyFieldFormatItem.type + '_' + row[col.field]} placement="bottom">{keyFieldFormatItem.memo}</Tooltip>
                                {:else}
                                <Button class={keyFieldFormatItem.class} on:click={keyFieldFormatItem.method(row[col.field])}><Icon name={keyFieldFormatItem.icon}></Icon></Button>
                                {/if}
                                &nbsp;
                            {:else}
                                {row[col.field]}
                            {/if}
                        {/each}
                        </td>
                    {:else}
                        <td>{row[col.field]}</td>
                    {/if}                
                {/each}                
            </tr>        
            {/each}
        </tbody>

    </Table>
    {/if}

</div>
