// frontend-k/src/routes/prog001d0001/create/+page.svelte
<script>
import { onMount, onDestroy } from 'svelte';    
import { goto } from '$app/navigation';
import { 
    FormGroup, Input, Label, Button, Icon
} from 'sveltestrap';
import { toast, SvelteToast } from '@zerodevx/svelte-toast';
import Swal from 'sweetalert2';
import { 
    getProgItem, getAxiosInstance, 
    getToastDefaultTheme, getToastErrorTheme, getToastWarningTheme, getToastSuccessTheme, getUrlNoStartSign,
    invalidFeedback, checkInvalid
} from "../../../components/BaseHelper.svelte";
import Toolbar from "../../../components/Toolbar.svelte";
import { PageConstants } from '../config';

let toolbarParam = {
    id          : PageConstants.CreateId,
    description : '站台測試用，新增資料作業.',
    methods     : {
        "back"      :   function() {
            goto( getUrlNoStartSign(getProgItem(PageConstants.QueryId).url) );
        }
        ,
        "refresh"   :   function() {
            btnClear();
        }
        ,
        "save"      :   function() {
            btnSave();
        } 
    }
}

var formParam = {
    'sysId'         :   '',
    'name'          :   '',
    'host'          :   '',
    'contextPath'   :   '',
    'isLocal'       :   'N',
    'icon'          :   'SYSTEM'
}

var checkFields = new Object();

onMount(()=>{

});

onDestroy(()=> {
    toast.pop(0);
});

function btnSave() {
    checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();      
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
            checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.push(response.data.message, getToastWarningTheme());
                return;
            }            
            toast.push(response.data.message, getToastSuccessTheme());   
            btnClear();
        } else {
            toast.push('error, null', getToastErrorTheme());
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    }); 
}

function btnClear() {
    checkFields = new Object();
    formParam.sysId = '';
    formParam.name = '';
    formParam.host = '';
    formParam.contextPath = '';
}

</script>

<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Toolbar args={toolbarParam}></Toolbar>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="sysId">編號</Label>
            <Input
            type="text"
            id="sysId"
            placeholder="輸入編號"     
            feedback={invalidFeedback('sysId', checkFields)}
            invalid={checkInvalid('sysId', checkFields)}
            bind:value={formParam.sysId}     
            />
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="name">名稱</Label>
            <Input
            type="text"
            id="name"
            placeholder="輸入名稱"     
            feedback={invalidFeedback('name', checkFields)}
            invalid={checkInvalid('name', checkFields)}
            bind:value={formParam.name}     
            />
        </FormGroup> 
    </div>    
</div>        
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="host">Host</Label>
            <Input
            type="text"
            id="host"
            placeholder="輸入Host"     
            feedback={invalidFeedback('host', checkFields)}
            invalid={checkInvalid('host', checkFields)}
            bind:value={formParam.host}     
            />
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="name">Context path</Label>
            <Input
            type="text"
            id="contextPath"
            placeholder="輸入Context path"     
            feedback={invalidFeedback('contextPath', checkFields)}
            invalid={checkInvalid('contextPath', checkFields)}
            bind:value={formParam.contextPath}     
            />
        </FormGroup> 
    </div>    
</div>  
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Button color="primary" on:click={btnSave}><Icon name="save"/>&nbsp;儲存</Button>
        &nbsp;
        <Button color="primary" on:click={btnClear}><Icon name="eraser"/>&nbsp;清除</Button>
    </div>
</div>    

<SvelteToast></SvelteToast>

// frontend-v-nx/pages/prog001d0001/create.vue
<script>
import Swal from 'sweetalert2';
import { toast } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

import Toolbar from '@/components/Toolbar.vue';
import { PageConstants } from './config';
import { 
	getAxiosInstance, 
	invalidFeedback,
	checkInvalid,
	escapeQifuHtmlMsg
} from '../../components/BaseHelper';

definePageMeta({ middleware : ['auth'] });

let checkFields = new Object();

export default {
	components: { Toolbar },
	setup() { 
	},
	data() {
		return {
			pageProgramId : PageConstants.CreateId,
			checkFields,
			formParam : {
				sysId : '',
				name : '',
				host : '',
				contextPath : '',
				isLocal : 'N',
				icon : 'SYSTEM'
			}
		}
	},
	methods: { 
		fieldInvalidFeedback : invalidFeedback,
		fieldCheckInvalid : checkInvalid,
		btnBack : function() {
			this.$router.back();
		},
		btnSave : _btnSave,
		btnClear : function() {
			this.checkFields = new Object();
			this.formParam.sysId = '';
			this.formParam.name = '';
			this.formParam.host = '';
			this.formParam.contextPath = '';
		}
	},
	created() { 
	},
	mounted() { 
	}
}

function _btnSave() {
    this.checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();      
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', this.formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
			this.checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.warning(escapeQifuHtmlMsg(response.data.message));
                return;
            }            
            toast.success(response.data.message);   
            this.btnClear();
        } else {
            toast.error('error, null');
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    });
}

</script>

<template>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<Toolbar 
			:progId="this.pageProgramId" 
        	description="站台測試用，新增資料作業." 
        	marginBottom="Y"
        	refreshFlag="Y"
        	@refreshMethod="btnClear"
        	backFlag="Y"
        	@backMethod="btnBack"
        	createFlag="N"
        	@createMethod="null"
        	saveFlag="Y"
        	@saveMethod="btnSave"
    	></Toolbar>		
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="sysId" class="form-label">編號</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('sysId', checkFields) ? 'is-invalid' : ' ')" id="sysId" placeholder="輸入編號" v-model="this.formParam.sysId">
		<div v-if="fieldCheckInvalid('sysId', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('sysId', checkFields) }}</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="name" class="form-label">名稱</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('name', checkFields) ? 'is-invalid' : ' ')" id="name" placeholder="輸入名稱" v-model="this.formParam.name">
		<div v-if="fieldCheckInvalid('name', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('name', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="host" class="form-label">Host</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('host', checkFields) ? 'is-invalid' : ' ')" id="host" placeholder="輸入Host" v-model="this.formParam.host">
		<div v-if="fieldCheckInvalid('host', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('host', checkFields) }}</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="contextPath" class="form-label">Context path</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('contextPath', checkFields) ? 'is-invalid' : ' ')" id="contextPath" placeholder="輸入Context path" v-model="this.formParam.contextPath">
		<div v-if="fieldCheckInvalid('contextPath', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('contextPath', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
    	<button type="button" class="btn btn-primary" v-on:click="btnSave"><i class="'bi bi-save"></i>&nbsp;儲存</button>
    	&nbsp;
    	<button type="button" class="btn btn-primary" v-on:click="btnClear"><i class="'bi bi-eraser"></i>&nbsp;清除</button>		
	</div>
</div>
</template>
