// frontend-v-nx/pages/nopermission.vue

<template>
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">
    
        <div class="card text-center">
          <div class="card-header">
            <i class="bi bi-cone-striped"></i>&nbsp;Permission denied.
          </div>
          <div class="card-body">
            <p class="card-text">
                <h5>{{ $route.redirectedFrom?.path }}</h5>
                <br>
                Permission denied，沒有操作權限。
                <br>          
            </p>
          </div>
          <div class="card-footer text-muted">
            &nbsp;
          </div>
        </div>
        </div>  
    </div>
    </template>

// frontend-k/src/routes/nopermission/+page.svelte
<script>
import { onMount, onDestroy } from 'svelte';
import { 
    Card,
    CardBody,
    CardFooter,
    CardHeader,
    CardText,
    CardTitle,
    Icon
} from 'sveltestrap';

onMount(()=>{
    
});
onDestroy(()=>{
    
});

</script>

<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
        <Card class="mb-3">
            <CardHeader>
                <CardTitle><Icon name="cone-striped" />&nbsp;Permission denied.</CardTitle>
            </CardHeader>
            <CardBody>
                <CardText>
                    Permission denied，沒有操作權限。
                </CardText>
            </CardBody>
            <CardFooter>&nbsp;</CardFooter>
        </Card>
	</div>  
</div>
