// frontend-v/src/components/GridPagination.vue
<script>
import { ref, watch } from 'vue';
import { getProgItem } from './BaseHelper';

export default {
    props: [ 'progId', 'changePageSelectMethod', 'changeGridConfigRowMethod', 'gridConfig' ],
    setup(props) {
    },
    data() {
        return {
            pageProg : null,
            prevPage : 1,
            nexPage : 1,
            lastPage : 1,
            midMaxShow : 3,
            pStart : 0,
            pEnd : 0,
            pItem : [],
            gBtnChangeRow1st : ' ',
            gBtnChangeRow2st : ' ',
            gBtnChangeRow3st : ' ',
            gBtnChangeRow4st : ' ',
        }
    },
    methods: {
    },
    created() {
        this.pageProg = getProgItem(this.progId);
        if (null == this.pageProg) {
            alert('Please close this page, GridPagination load fail!');
            window.location = "/";
        }
        
        if (10 == this.gridConfig.row) { 
            this.gBtnChangeRow1st = ' active ';
        }
        if (30 == this.gridConfig.row) {
            this.gBtnChangeRow2st = ' active ';
        }
        if (50 == this.gridConfig.row) {
            this.gBtnChangeRow3st = ' active ';
        }
        if (100 == this.gridConfig.row) {
            this.gBtnChangeRow4st = ' active ';
        }

        watch(() => this.gridConfig.row, (newVal, oldVal) => {
            if (10 == this.gridConfig.row) {
                this.gBtnChangeRow1st = ' active ';
                this.gBtnChangeRow2st = ' ';
                this.gBtnChangeRow3st = ' ';
                this.gBtnChangeRow4st = ' ';
            }
            if (30 == this.gridConfig.row) { 
                this.gBtnChangeRow1st = ' ';
                this.gBtnChangeRow2st = ' active ';
                this.gBtnChangeRow3st = ' ';
                this.gBtnChangeRow4st = ' ';
            }
            if (50 == this.gridConfig.row) { 
                this.gBtnChangeRow1st = ' ';
                this.gBtnChangeRow2st = ' ';
                this.gBtnChangeRow3st = ' active ';
                this.gBtnChangeRow4st = ' ';
            }
            if (100 == this.gridConfig.row) { 
                this.gBtnChangeRow1st = ' ';
                this.gBtnChangeRow2st = ' ';
                this.gBtnChangeRow3st = ' ';
                this.gBtnChangeRow4st = ' active ';
            }
        });

        watch(() => this.gridConfig.total, (newVal, oldVal) => {
            this.pItem = [];
            if (this.gridConfig.total > 0) {
                this.prevPage = this.gridConfig.page - 1;
                this.nexPage = this.gridConfig.page + 1;
                this.lastPage = parseInt( this.gridConfig.total / this.gridConfig.row );
                if (parseInt(this.gridConfig.total % this.gridConfig.row) != 0) {
                    this.lastPage += 1;
                }
                if (this.gridConfig.page > this.lastPage) {
                    this.gridConfig.page = this.lastPage;
                    this.prevPage = this.gridConfig.page - 1;
                    this.nexPage = this.gridConfig.page + 1;
                }
                if (this.gridConfig.page < 1) {
                    this.gridConfig.page = 1;
                    this.prevPage = 1;
                    this.nexPage = 1;
                }
                if (this.prevPage < 1) {
                    this.prevPage = 1;
                }
                if (this.nexPage > this.lastPage) {
                    this.nexPage = this.lastPage;
                }
                this.pStart = this.gridConfig.page - this.midMaxShow;
                this.pEnd = this.gridConfig.page + this.midMaxShow;
                if (this.pStart < 1) { 
                    this.pStart = 1;
                }
                if (this.pEnd > this.lastPage) {
                    this.pEnd = this.lastPage;
                }
                for (let i = this.pStart; i <= this.pEnd; i++) {
                    this.pItem.push(i);
                }
            }
            
        });

    },
    mounted() {
    }
}

</script>
<template>
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <table v-if=" this.gridConfig != null && this.gridConfig.total > 0 " width="100%" border="0" cellspacing="0" cellpadding="1" >
            <tr>
                <td  width="70%" align="left" valign="middle">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li class="page-item" @click="this.changePageSelectMethod(1)">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item" @click="this.changePageSelectMethod(this.prevPage)">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true">&lsaquo;</span>
                                </a>
                            </li>
                            <li v-for="pNum in pItem" class="page-item" @click="this.changePageSelectMethod(pNum)"><a class="page-link" href="#">{{pNum}}</a></li>
                            <li class="page-item" @click="this.changePageSelectMethod(this.nexPage)">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true">&rsaquo;</span>
                                </a>
                            </li>
                            <li class="page-item" @click="this.changePageSelectMethod(this.lastPage)">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul> 
                    </nav>       	      
	            </td>   
                <td width="30%" align="right" valign="middle">
                    <table width="100%" border="0" cellspacing="0" cellpadding="1" >
                        <tr>
                            <td align="right">
                                <div class="btn-group me-2" role="group" aria-label="Second group">
                                    <button type="button" v-bind:class="'btn btn-secondary ' + this.gBtnChangeRow1st" @click="changeGridConfigRowMethod(10)">10</button>
                                    <button type="button" v-bind:class="'btn btn-secondary ' + this.gBtnChangeRow2st" @click="changeGridConfigRowMethod(30)">30</button>
                                    <button type="button" v-bind:class="'btn btn-secondary ' + this.gBtnChangeRow3st" @click="changeGridConfigRowMethod(50)">50</button>
                                    <button type="button" v-bind:class="'btn btn-secondary ' + this.gBtnChangeRow4st" @click="changeGridConfigRowMethod(100)">100</button>
                                </div>
                            </td>
                            <td align="left">
                                <h6>
                                    Total
                                    <span class="badge text-bg-info">{{this.gridConfig.total}}</span>
                                </h6>
                            </td>
                        </tr>
                    </table>
                </td>             
            </tr>
        </table>
    </div>
</div>
</template>

// frontend/src/components/GridPagination.svelte
<script>
import { 
    Pagination, PaginationItem, PaginationLink, Button, ButtonGroup, Badge 
} from 'sveltestrap';

export let changeGridConfigRowMethod;
export let changePageSelectMethod;
export let gridConfig;

let prevPage = 1;
let nexPage = 1;
let lastPage = 1;

let midMaxShow = 3;
let pStart;
let pEnd;
let pItem = [];

$ : {  
	pItem = [];
  	if (gridConfig.total > 0) {
    	prevPage = gridConfig.page - 1;
    	nexPage = gridConfig.page + 1;
    	lastPage = parseInt( gridConfig.total / gridConfig.row );
    	if (parseInt(gridConfig.total % gridConfig.row) != 0) {
      		lastPage += 1;
    	}
    	if (gridConfig.page > lastPage) {
      		gridConfig.page = lastPage;
      		prevPage = gridConfig.page - 1;
      		nexPage = gridConfig.page + 1;      
    	}
    	if (gridConfig.page < 1) {
      		gridConfig.page = 1;
      		prevPage = 1;
      		nexPage = 1;
    	}    
    	if (prevPage < 1) {
      		prevPage = 1;
    	}
    	if (nexPage > lastPage) {
      		nexPage = lastPage;
    	}
    	pStart = gridConfig.page - midMaxShow;
    	pEnd = gridConfig.page + midMaxShow;
    	if (pStart < 1) { 
      		pStart = 1;
    	}
    	if (pEnd > lastPage) {
      		pEnd = lastPage;
    	}
    	for (let i = pStart; i <= pEnd; i++) {
      		pItem.push(i);
    	}
	}
}

</script>

<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
    {#if gridConfig != null && gridConfig.total > 0 }
    <table width="100%" border="0" cellspacing="0" cellpadding="1" >
		<tr>
			<td  width="70%" align="left" valign="middle">
				<Pagination ariaLabel="Page navigation">
	            	<PaginationItem>
	                	<PaginationLink first href={window.location} on:click={changePageSelectMethod(1)} />
	              	</PaginationItem>
	              	<PaginationItem>
	                	<PaginationLink previous href={window.location} on:click={changePageSelectMethod(prevPage)} />
	              	</PaginationItem>
	
	              	{#each pItem as pNum }
	              	<PaginationItem active={ pNum == gridConfig.page } >
	                	<PaginationLink href={window.location} on:click={changePageSelectMethod(pNum)}>{pNum}</PaginationLink>
	              	</PaginationItem> 
	              	{/each}
	
	              	<PaginationItem>
	                	<PaginationLink next href={window.location} on:click={changePageSelectMethod(nexPage)} />
	              	</PaginationItem>
	              	<PaginationItem>
	                	<PaginationLink last href={window.location} on:click={changePageSelectMethod(lastPage)} />
	              	</PaginationItem>    
	          	</Pagination>        	      
	        </td>
	        <td width="30%" align="right" valign="middle">
	        	<table width="100%" border="0" cellspacing="0" cellpadding="1" >
	            	<tr>
	              		<td align="right">
	                		<ButtonGroup>
	                  		{#if gridConfig.row == 10 }
	                    		<Button active on:click={changeGridConfigRowMethod(10)}>Row 10</Button>
	                  		{:else}
	                    		<Button on:click={changeGridConfigRowMethod(10)}>Row 10</Button>
	                  		{/if}
	                  
	                  		{#if gridConfig.row == 30 }
	                    		<Button active on:click={changeGridConfigRowMethod(30)}>30</Button>
	                  		{:else}
	                    		<Button on:click={changeGridConfigRowMethod(30)}>30</Button>
	                  		{/if}
	                  
	                  		{#if gridConfig.row == 50 }
	                    		<Button active on:click={changeGridConfigRowMethod(50)}>50</Button>
	                  		{:else}
	                    		<Button on:click={changeGridConfigRowMethod(50)}>50</Button>
	                  		{/if}
	      
	                  		{#if gridConfig.row == 100 }
	                    		<Button active on:click={changeGridConfigRowMethod(100)}>100</Button>
	                  		{:else}
	                    		<Button on:click={changeGridConfigRowMethod(100)}>100</Button>
	                  		{/if}
	                		</ButtonGroup>
	              		</td>
	              		<td align="left">
	                		<h6>
	                  			Total
	                  			<Badge color="info">{gridConfig.total}</Badge>
	                		</h6>
	              		</td>
	            	</tr>
				</table>    
	        </td>        
		</tr>
    </table>  
    {:else}
      &nbsp;
    {/if}
    
  	</div>
</div>
