// frontend-k/src/routes/prog001d0005/create/+page.svelte
<script>
import { onMount, onDestroy } from 'svelte';    
import { goto } from '$app/navigation';
import { 
    FormGroup, Input, Label, Button, Icon
} from 'sveltestrap';
import { toast, SvelteToast } from '@zerodevx/svelte-toast';
import Swal from 'sweetalert2';
import { 
    getProgItem, getAxiosInstance, 
    getToastDefaultTheme, getToastErrorTheme, getToastWarningTheme, getToastSuccessTheme, getUrlNoStartSign,
    invalidFeedback, checkInvalid,
    getFile2Base64
} from "../../../components/BaseHelper.svelte";
import Toolbar from "../../../components/Toolbar.svelte";
import { PageConstants } from '../config';

let toolbarParam = {
    id          : PageConstants.CreateId,
    description : 'Jasperreport resources管理，新增資料作業.',
    methods     : {
        "back"      :   function() {
            goto( getUrlNoStartSign(getProgItem(PageConstants.QueryId).url) );
        }
        ,
        "refresh"   :   function() {
            btnClear();
        }
        ,
        "save"      :   function() {
            btnSave();
        } 
    }
}

let files, input;
let currFileBase64Content;
var formParam = {
    'reportId'      :   '',
    'description'   :   '',
    'isCompile'     :   'N',
    'compile'       :   false,
    'uploadBase64'  :   '',
    'file'          :   ''
}

$ : {
    if (formParam.compile) {
        formParam.isCompile = 'Y';
    } else {
        formParam.isCompile = 'N';
    }

    if (files != null && files.length > 0) {
        if (files[0].size > 1 && files[0].size <= import.meta.env.VITE_UPLOAD_MAX_SIZE ) {
            getFile2Base64(files[0]).then(c => { 
                currFileBase64Content = c;
            }).catch(e => { 
                currFileBase64Content = ''; 
            });            
        }
    }
}

var checkFields = new Object();

onMount(()=>{
    
});

onDestroy(()=>{
	toast.pop(0);
});

function btnSave() {
    checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();      
    formParam.uploadBase64 = currFileBase64Content;
    if (files != null && files.length > 0) {
        if (files[0].size < 1 || files[0].size > import.meta.env.VITE_UPLOAD_MAX_SIZE ) {
            Swal.hideLoading();
            Swal.close();           
            toast.push('檔案大小超過規範', getToastWarningTheme());    
            return;
        }
        if (!files[0].name.toLowerCase().endsWith('.zip')) {
            Swal.hideLoading();
            Swal.close();           
            toast.push('只允許上傳zip檔案', getToastWarningTheme());               
            return;
        }
        formParam.file = files[0].name;
    }
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
            checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.push(response.data.message, getToastWarningTheme());
                return;
            }            
            toast.push(response.data.message, getToastSuccessTheme());   
            btnClear();
        } else {
            toast.push('error, null', getToastErrorTheme());
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    }); 
}

function btnClear() {
    checkFields = new Object();
    formParam.reportId = '';
    formParam.description = '';
    formParam.compile = false;
    formParam.isCompile = 'N';
    formParam.file = '';
    currFileBase64Content = '';
    input.value = '';
}

</script>

<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Toolbar args={toolbarParam}></Toolbar>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="reportId">報表編號</Label>
            <Input type="text" id="reportId" placeholder="輸入報表編號" feedback={invalidFeedback('templateId', checkFields)} invalid={checkInvalid('reportId', checkFields)} bind:value={formParam.reportId} />
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="jasperZipFile">jasperreport資源zip壓縮檔</Label>
            <input type="file" class="form-control" id="jasperZipFile" bind:files bind:this={input} feedback={invalidFeedback('file', checkFields)} invalid={checkInvalid('file', checkFields)} />
        </FormGroup>
    </div>    
</div>
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <FormGroup>
            <Input id="compile" type="switch" label="編譯jrxml" bind:checked={formParam.compile} />            
        </FormGroup>         
    </div>    
</div>
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <FormGroup>
            <Label for="description">說明</Label>
            <Input type="textarea" id="description" row="3" col="25" bind:value={formParam.description} />            
        </FormGroup>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Button color="primary" on:click={btnSave}><Icon name="save"/>&nbsp;儲存</Button>
        &nbsp;
        <Button color="primary" on:click={btnClear}><Icon name="eraser"/>&nbsp;清除</Button>
    </div>
</div>    

<SvelteToast></SvelteToast>

// frontend-v-nx/pages/prog001d0005/create.vue
<script>
import { ref, watch } from 'vue';
import Swal from 'sweetalert2';
import { toast } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

import Toolbar from '@/components/Toolbar.vue';
import { PageConstants } from './config';
import { 
	getAxiosInstance, 
	invalidFeedback,
	checkInvalid,
	escapeQifuHtmlMsg,
	getFile2Base64
} from '../../components/BaseHelper';

definePageMeta({ middleware : ['auth'] });

let checkFields = new Object();

export default {
	components: { Toolbar },
	setup() { 
	},
	data() {
		return {
			pageProgramId : PageConstants.CreateId,
			checkFields,
			formParam : {
				reportId : '',
				description : '',
				isCompile : 'N',
				compile : false,
				uploadBase64 : '',
				file : ''
			}
		}
	},
	methods: { 
		fieldInvalidFeedback : invalidFeedback,
		fieldCheckInvalid : checkInvalid,
		btnBack : function() {
			this.$router.back();
		},
		btnSave : _btnSave,
		btnClear : function() {
			this.checkFields = new Object();
			this.formParam.reportId = '';
			this.formParam.description = '';
			this.formParam.isCompile = 'N';
			this.formParam.compile = false;
			this.formParam.uploadBase64 = '';
			this.formParam.file = '';
			document.getElementById('file').value = null;
		},
		handleFiles : function(event) {
			this.formParam.uploadBase64 = '';
			this.formParam.file = '';
			var files = event.target.files;
			if (files == null || files.length < 1) {
				toast.warning('請選取檔案');
				event.target.value = null;
			}
			if (files != null && files.length > 0) {
				if (!files[0].name.toLowerCase().endsWith('.zip')) {
					toast.warning('只允許上傳zip檔案');
					event.target.value = null;
				}
				if (files[0].size > 1 && files[0].size <= import.meta.env.VITE_UPLOAD_MAX_SIZE ) {
					getFile2Base64(files[0]).then(c => { 
						this.formParam.uploadBase64 = c;
						this.formParam.file = files[0].name;
					}).catch(e => { 
						this.formParam.uploadBase64 = ''; 
						toast.error('請重新選取檔案,發生錯誤');
						event.target.value = null;
					});            
				} else {
					toast.warning('選取之檔案,容量不允許上傳');
					event.target.value = null;
				}
			}
		},
		refreshSwitchItemVariableFn : function() {
			if (this.formParam.compile) {
				this.formParam.isCompile = 'Y';
			} else {
				this.formParam.isCompile = 'N';
			}
		}
	},
	created() { 
		this.refreshSwitchItemVariableFn();
        watch(() => this.formParam.compile, (newVal, oldVal) => {
            this.refreshSwitchItemVariableFn();
        });
	},
	mounted() { 
	}
}

function _btnSave() {
    this.checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', this.formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
			this.checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.warning(escapeQifuHtmlMsg(response.data.message));
                return;
            }            
            toast.success(response.data.message);   
            this.btnClear();
        } else {
            toast.error('error, null');
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    });
}

</script>

<template>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<Toolbar 
			:progId="this.pageProgramId" 
        	description="Jasperreport resources管理，新增資料作業." 
        	marginBottom="Y"
        	refreshFlag="Y"
        	@refreshMethod="btnClear"
        	backFlag="Y"
        	@backMethod="btnBack"
        	createFlag="N"
        	@createMethod="null"
        	saveFlag="Y"
        	@saveMethod="btnSave"
    	></Toolbar>		
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="reportId" class="form-label">報表編號</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('reportId', checkFields) ? 'is-invalid' : ' ')" id="reportId" placeholder="輸入報表編號" v-model="this.formParam.reportId">
		<div v-if="fieldCheckInvalid('reportId', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('reportId', checkFields) }}</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="file" class="form-label">jasperreport資源zip壓縮檔</label>
		<input type="file" v-bind:class="'custom-file-input form-control ' + ( fieldCheckInvalid('file', checkFields) ? 'is-invalid' : ' ')" id="file" placeholder="輸入名稱" @change="handleFiles" multiple>
		<div v-if="fieldCheckInvalid('file', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('file', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<div class="form-check form-switch">
			<input class="form-check-input" type="checkbox" role="switch" id="compile" v-model="this.formParam.compile">
			<label class="form-check-label" for="compile">編譯jrxml</label>
		</div>		
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<label for="description" class="form-label">說明</label>
		<textarea class="form-control" id="description" row="3" col="25" v-model="this.formParam.description"></textarea>			
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
    	<button type="button" class="btn btn-primary" v-on:click="btnSave"><i class="'bi bi-save"></i>&nbsp;儲存</button>
    	&nbsp;
    	<button type="button" class="btn btn-primary" v-on:click="btnClear"><i class="'bi bi-eraser"></i>&nbsp;清除</button>		
	</div>
</div>
</template>
