// frontend-v-nx/pages/login.vue
<script>
import { useBaseStore } from '../store/baseStore'
import Swal from 'sweetalert2';
import { toast } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

import { setRefreshAndAccessTokenCookie, userLogoutClearCookie } from '../components/BaseHelper';

export default {
    setup(props) {
        const baseStore = useBaseStore();
        return {
            baseStore
        }
    },    
    data() {
        return {
            userId  :   '',
            passwd  :   '',
            message :   ''
        }
    },
    methods: {
        loginBtnClick : function() {
            Swal.fire({
                title: "Loading...",
                html: "請等待",
                showConfirmButton: false,
                allowOutsideClick: false
            });
            Swal.showLoading();

            this.message = '';
            fetch(import.meta.env.VITE_API_URL + '/auth/signin', {
                method: "POST",
		        headers: {
			        "Content-Type": "application/json",
		        },
		        body: JSON.stringify({
			        username: this.userId,
			        password: this.passwd
		        }),
		        signal: AbortSignal.timeout(import.meta.env.VITE_FETCH_TIMEOUT)
	        })
	        .then(response => {
		        Swal.hideLoading();
		        Swal.close();
		        if (response.ok) {
			        return response.json();
		        }
		        throw new Error(response.status + ' ' + response.statusText);
	        })
	        .then((responseJson) => {
                var that = this;
		        if (null != responseJson) {
                    this.baseStore.setUserData(responseJson);
                    setRefreshAndAccessTokenCookie(responseJson.refreshToken, responseJson.accessToken);               
                    that.$router.push('/');
		        } else {
                    this.baseStore.clearUserData();
                    userLogoutClearCookie();
		        }
	        })
	        .catch((error) => {
                userLogoutClearCookie();
		        console.log(error);
                this.message = error;
	        	this.userId = '';
                this.passwd = '';
		        Swal.hideLoading();
		        Swal.close();
	        });
        }
    },
    mounted() {
    }
}
</script>
<template>
<div class="login-body">
    <section class="login-content">
        <div class="login-box">
			<div class="login-form">
				<h3 class="login-head">
					<!-- <img src="resource/logo.svg" width="250px" style="margin-bottom:10px" /> -->
					<i class="bi bi-person-circle"></i>
					qífū - frontend
				</h3>
                <div class="form-group">
                    <label for="username">帳戶</label>
                    <input type="text" class="form-control" id="username" placeholder="Account" v-model="this.userId">
                </div>
                <div class="form-group">
					<label for="password">密碼</label>
					<input class="form-control" type="password" name="password" id="password" placeholder="Password" v-model="this.passwd" />
                </div>
                <div class="form-group">
                    <p></p>
                    <button type="button" class="btn btn-primary col-12" v-on:click="loginBtnClick"><i class="bi bi-box-arrow-in-right"></i>&nbsp;登入</button>
                </div>
                <div v-if=" this.message != null && '' != this.message ">
                    <h6><span class="badge bg-danger">{{this.message}}</span></h6>
                </div>
            </div>
        </div>
    </section>
</div>                
</template>

// frontend-k/src/routes/login/+page.svelte
<script>
import {
	Icon,
	Button,
	Badge,
	Label,
	Input,
	FormGroup
} from 'sveltestrap';
import { goto } from '$app/navigation';
import Swal from 'sweetalert2';
import { _user } from '../../store/userStore.js';
import { setRefreshAndAccessTokenCookie } from '../../components/BaseHelper.svelte';

let userData;
_user.subscribe(value => {
	userData = value;
});

let lgParam = {
	username: '',
	password: '',
	message: ''
}

function loginClick() {
	Swal.fire({
		title: "Loading...",
		html: "請等待",
		showConfirmButton: false,
		allowOutsideClick: false
	});
	Swal.showLoading();

	lgParam.message = '';
	fetch(import.meta.env.VITE_API_URL + '/auth/signin', {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify({
			username: lgParam.username,
			password: lgParam.password
		}),
		signal: AbortSignal.timeout(import.meta.env.VITE_FETCH_TIMEOUT)
	})
	.then(response => {
		Swal.hideLoading();
		Swal.close();
		if (response.ok) {
			return response.json();
		}
		throw new Error(response.status + ' ' + response.statusText);
	})
	.then((responseJson) => {
		if (null != responseJson) {
			_user.update((val) => {
				return responseJson;
			});
		} else {
			_user.update((val) => {
				return {};
			});
		}
		setRefreshAndAccessTokenCookie(userData.refreshToken, userData.accessToken);
		goto('/about');
	})
	.catch((error) => {
		console.log(error);
		lgParam.message = error;
		lgParam.username = '';
		lgParam.password = '';
		Swal.hideLoading();
		Swal.close();
	});
}

</script>    

<div class="login-body">
    <section class="login-content">
        <div class="login-box">
			<div class="login-form">
            
				<h3 class="login-head">
					<!-- <img src="resource/logo.svg" width="250px" style="margin-bottom:10px" /> -->
					<Icon name="person-circle"/>
					qífū - frontend
				</h3>
				<FormGroup>
					<Label for="username">帳戶</Label>
					<Input type="text" name="username" id="username" placeholder="Account" bind:value={lgParam.username} />
				</FormGroup>
				<FormGroup>
					<Label for="password">密碼</Label>
					<input class="form-control" type="password" name="password" id="password" placeholder="Password" bind:value={lgParam.password} />
				</FormGroup>

				<FormGroup>
					<div>
						<Button color="primary" class="col-12" on:click="{loginClick}"><Icon name="box-arrow-in-right"/>&nbsp;登入</Button>
					</div>
				</FormGroup>
				
				{#if null != lgParam && null != lgParam.message && '' != lgParam.message }
				<p class="form-text"><Badge color='danger'>{lgParam.message}</Badge></p>
				{/if}
						
			</div>	
		</div>
	</section>
</div>
