// frontend-k/src/components/Toolbar.svelte
<script>
import { Icon, Tooltip } from "sveltestrap";
import { onMount } from 'svelte';    
import { getProgItem } from "../components/BaseHelper.svelte";

export let args = {};

let pageProg = {};


onMount(()=>{        
    pageProg = getProgItem(args.id);    
    if (null == pageProg) {
        //window.location.href = '/';
		pageProg = {
			'name'	:	'unknown',
			'fontIconClassId'	:	'globe2'
		};
    }
});

</script>

<div class="app-title" style="background: linear-gradient(to top, #f8f9fa, #ffffff); width: 103vw; overflow: hidden;">
	<div>
		<h1 style="color: #003366;"><Icon name={pageProg.fontIconClassId}/>&nbsp;{pageProg.name}</h1>

		<p style="color: #333300;">{args.description}</p>

		<div>		

		{#if null != args.methods && (typeof args.methods.back === 'function') }	
			<Icon name="arrow-left-square" class="btn btn-secondary btn-sm" id="tb_back" onclick={args.methods.back} />
			<Tooltip target="tb_back" placement="bottom">上一頁</Tooltip>
			&nbsp;
		{/if}				

		{#if null != args.methods && (typeof args.methods.refresh === 'function') }	
			<Icon name="repeat" class="btn btn-secondary btn-sm" id="tb_repeat" onclick={args.methods.refresh} />
			<Tooltip target="tb_repeat" placement="bottom">刷新</Tooltip>
			&nbsp;
		{/if}	

		{#if null != args.methods && (typeof args.methods.create === 'function') }
			<Icon name="plus-circle" class="btn btn-secondary btn-sm" id="tb_plus" onclick={args.methods.create} />
			<Tooltip target="tb_plus" placement="bottom">新增頁</Tooltip>
			&nbsp;
		{/if}	

		{#if null != args.methods && (typeof args.methods.save === 'function') }
            <Icon name="save" class="btn btn-secondary btn-sm" id="tb_save" onclick={args.methods.save} />
			<Tooltip target="tb_save" placement="bottom">儲存/更新</Tooltip>
			&nbsp;
		{/if}	
				
		</div>
	</div>    
	

        		
</div> 

{#if (undefined === args.marginBottom) || null == args.marginBottom || args.marginBottom }
<p style="margin-bottom: 5px"></p>
{/if}

// frontend-v-nx/components/Toolbar.vue
<script>
import { getProgItem } from './BaseHelper';

export default {
    props: [
        'progId', 'description', 
        'marginBottom',
        'refreshFlag', 'refreshMethod', 
        'backFlag', 'backMethod', 
        'createFlag', 'createMethod',
        'saveFlag', 'saveMethod',
        'queryFieldShowSwitchFlag', 'queryFieldShowSwitcMethod'
    ],
    emits: ["refreshMethod", "backMethod", "createMethod", "saveMethod", "queryFieldShowSwitcMethod"],
    setup(props) {
    },    
    data() {
        return { 
            pageProg : null,
            switchEye : true
        }
    },
    methods: {
        fnBack : function() {
            this.$emit('backMethod');
        },        
        fnRefresh : function() {
            this.$emit('refreshMethod');
        },
        fnCreate : function() {
            this.$emit('createMethod');
        },
        fnSave : function() {
            this.$emit('saveMethod');
        },
        fnQueryFieldShowSwitch : function() {
            this.switchEye = !this.switchEye;
            this.$emit('queryFieldShowSwitcMethod');
        }
    },
    created() {
        this.pageProg = getProgItem(this.progId);
        if (null == this.pageProg) {
            //alert('Please close this page, toolbar load fail!');
            //window.location = "/";
            console.log('error, pageProg null');
        }
        //console.log(this.pageProg);
    },
    mounted() {
        /*
        this.pageProg = getProgItem(this.progId);
        if (null == this.pageProg) {
            alert('Please close this page, toolbar load fail!');
        }
        console.log(this.pageProg);
        */
    }
}
</script>

<template>
<div class="app-title" style="background: linear-gradient(to top, #f8f9fa, #ffffff); width: 103vw; overflow: hidden;">
	<div>
		<h1 style="color: #003366;"><i v-bind:class="'bi bi-'+this.pageProg.fontIconClassId"></i>&nbsp;{{this.pageProg.name}}</h1>
		<p style="color: #333300;">{{this.description}}</p>
		<div>
            <i v-if=" 'Y' == this.backFlag" id="tb_back" class="bi bi-arrow-left-square btn btn-light btn-sm text-primary" @click="this.fnBack" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="上一頁" data-trigger="hover"></i>
            {{ 'Y' == this.backFlag ? '&nbsp;' : '' }}

            <i v-if=" 'Y' == this.refreshFlag" id="tb_repeat" class="bi bi-repeat btn btn-light btn-sm text-primary" @click="this.fnRefresh" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="刷新" data-trigger="hover"></i>
            {{ 'Y' == this.refreshFlag ? '&nbsp;' : '' }}

            <i v-if=" 'Y' == this.createFlag " id="tb_plus" class="bi bi-plus-circle btn btn-light btn-sm text-primary" @click="this.fnCreate" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="新增頁" data-trigger="hover"></i>
            {{ 'Y' == this.createFlag ? '&nbsp;' : '' }}

            <i class="bi bi-three-dots-vertical text-muted" v-if=" 'Y' == this.queryFieldShowSwitchFlag || 'Y' == this.saveFlag " ></i>

            <i v-if=" 'Y' == this.saveFlag " id="tb_save" class="bi bi-save btn btn-light btn-sm text-primary" @click="this.fnSave" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="儲存/更新" data-trigger="hover"></i>
            {{ 'Y' == this.saveFlag ? '&nbsp;' : '' }}

            <i v-if=" 'Y' == this.queryFieldShowSwitchFlag " id="tb_queryFieldShowSwitch" v-bind:class="'bi bi-' + (this.switchEye ? 'arrow-down-circle' : 'arrow-up-circle') + ' btn btn-light btn-sm'" @click="this.fnQueryFieldShowSwitch" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="顯示/隱藏查詢區塊" data-trigger="hover"></i>
            {{ 'Y' == this.queryFieldShowSwitchFlag ? '&nbsp;' : '' }}            
		</div>
	</div>    
</div> 
<p v-if=" 'Y' == this.marginBottom " style="margin-bottom: 5px"></p>
</template>
