// frontend-v-nx/pages/about.vue
<script>
definePageMeta({ middleware : ['auth'] });
</script>

<template>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">

    <div class="card text-center">
      <div class="card-header">
        <i class="bi bi-info-circle"></i>&nbsp;About
      </div>
      <div class="card-body">
        <p class="card-text">
            <h5>qífū&nbsp;-&nbsp;4</h5>
            <br>
            qífū4&nbsp;是一個前端使用&nbsp;VUE-3&nbsp;，&nbsp;後端使用&nbsp;springboot&nbsp;的一個範例網站程式。<br>
            主要為了當作內部OA系統，開發使用的平台的基底，而設計的程式。<br>
            <br>
            Contact:&nbsp;chen.xin.nien@gmail.com<br>
            GitHub:&nbsp;https://github.com/billchen198318/qifu4/<br>
            <br>          
        </p>
      </div>
      <div class="card-footer text-muted">
        ver 0.4
      </div>
    </div>
	</div>  
</div>
</template>

// frontend-various/frontend/src/pages/About.svelte
<script>
import { 
    Card,
    CardBody,
    CardFooter,
    CardHeader,
    CardText,
    CardTitle,
    Icon
} from 'sveltestrap';
</script>

<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
        <Card class="mb-3">
            <CardHeader>
                <CardTitle><Icon name="info-circle-fill" />&nbsp;About</CardTitle>
            </CardHeader>
            <CardBody>
                <CardText>
                    <h5>qífū&nbsp;-&nbsp;4</h5>
                    <br>
                    qífū4&nbsp;是一個前端使用&nbsp;Svelte&nbsp;，&nbsp;後端使用&nbsp;springboot&nbsp;的一個範例網站程式。<br>
                    主要為了當作內部OA系統，開發使用的平台的基底，而設計的程式。<br>
                    <br>
                    Contact:&nbsp;chen.xin.nien@gmail.com<br>
                    GitHub:&nbsp;https://github.com/billchen198318/qifu4/<br>
                    <br>
                </CardText>
            </CardBody>
            <CardFooter>ver 0.4</CardFooter>
        </Card>
	</div>  
</div>
