// frontend-v-nx/app.vue
<script>
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import './assets/vali.css';
import './assets/m.css';

import { watch } from "vue";
import { useBaseStore } from './store/baseStore';
import { 
  getAxiosInstance,
  getAccessTokenCookie, 
  getRefreshTokenCookie, 
  setRefreshAndAccessTokenCookie, 
  checkUserHasLogined, 
  userLogoutClearCookie, 
  checkHasPermission } from './components/BaseHelper';

import { createPopper } from '@popperjs/core';
import Swal from 'sweetalert2';

export default {
  setup() {
    const baseStore = useBaseStore();
    return { 
      baseStore
    }
  },
  data() {
    return { }
  },
  methods: {
    initTreeMenu              : _initTreeMenu,
    jsTreeMenuInit            : _jsTreeMenuInit,
    loadUserLoginedFromClient : _loadUserLoginedFromClient,
    clearUserLoginData        : _clearUserLoginData,
    userLogout                : _userLogout,
    reloadPageLogoClick       : function() {
      navigateTo('/');
    },
    showUserProfile           : function() {
      var str = 'User Id: ' + this.baseStore.user.id + '<br>Administrator: ' + this.baseStore.user.admin;
      str += '<br>Role: [ ';
      for (var r in this.baseStore.user.roleList) {
        str += this.baseStore.user.roleList[r].role + ',';
      }
      str += ' ]';
      Swal.fire({
        title: "User info",
        html: str,
        icon: "info"
      });     
    }
  },
  beforeCreate() {
  },
  created() {
    this.loadUserLoginedFromClient();
    this.$router.beforeEach((to, from, next) => {
      let pageUrl = to.path;
      if (pageUrl != '/nopermission' && pageUrl != '/about' && pageUrl != '/' && pageUrl != '/login') {
        if (checkHasPermission(to.path, true)) {
          next();
          return;
        }
      } else {
        next();
        return;
      }
      next({path : '/nopermission', replace : true});
    });    
    watch(() => this.baseStore.user.login, (newVal, oldVal) => {
      if ('Y' == newVal) {
        this.initTreeMenu();
      }
    });
  },
  mounted() {
    const nuxtApp = useNuxtApp();
    let bsToolTip = new nuxtApp.$bootstrap.Tooltip(document.body, {
      selector: "[data-bs-toggle='tooltip']",
      trigger : 'hover'
    });    
    document.addEventListener("mousedown", e => {
      if (null != bsToolTip) {
        //bsToolTip.hide(); // no work...
        const el = document.getElementsByClassName("tooltip bs-tooltip-auto fade show");
        if (null != el) {
          for (var n in el) {
            if (null == el[n]) { continue; }
            if (undefined == el[n].id) { continue; }
            if (null == el[n].id) { continue; }
            if (el[n].id.indexOf('tooltip') == 0) {
              el[n].remove();
            }
          }
        }
      }
    });

    this.$nextTick(() => {
      const button = document.querySelector('#button');
      const tooltip = document.querySelector('#tooltip');
      createPopper(button, tooltip);
    });

  },
  unmounted() {
    document.removeEventListener("mousedown");
  }
};

function _loadUserLoginedFromClient() {
  var ck_user_refresh_token = getRefreshTokenCookie();
  var ck_user_access_token = getAccessTokenCookie();
  let userData = this.baseStore.user;
  if (null == ck_user_refresh_token || '' == ck_user_refresh_token || null == ck_user_access_token || '' == ck_user_access_token) {
    this.$router.push('/login');
    return;
  }
  if (!checkUserHasLogined(userData) && (null != ck_user_refresh_token && '' != ck_user_refresh_token) && (null != ck_user_access_token && '' != ck_user_access_token)) {
    fetch(import.meta.env.VITE_API_URL + '/auth/validLogined', {
  			method: "POST",
  			headers: {
  				"Content-Type": "application/json",
  			},
  			body: JSON.stringify({
  				accessToken: ck_user_access_token,
  				refreshToken: ck_user_refresh_token
  			}),
  			signal: AbortSignal.timeout(import.meta.env.VITE_FETCH_TIMEOUT)
  	})
  	.then(response => {
  			if (response.ok) {
  				return response.json();
  			}
        this.clearUserLoginData();
  			throw new Error(response.status + ' ' + response.statusText);
  	})
  	.then((responseJson) => {
      if (null != responseJson) {
        if ('' == responseJson.accessToken || '' == responseJson.refreshToken) {
          this.clearUserLoginData();
          return;
        }
        this.baseStore.setUserData(responseJson);
        setRefreshAndAccessTokenCookie(userData.refreshToken, userData.accessToken);
        //this.initTreeMenu(); effect change in watch
      } else {
        this.clearUserLoginData();
        this.$router.push('/login');
  		}
  	})
  	.catch((error) => {
  			this.clearUserLoginData();
  			console.log(error);
  	});
  }
}

function _initTreeMenu() {
  var that = this;
  let userData = this.baseStore.user;
  let menuData = this.baseStore.menuList;
  if (menuData != null && menuData.length > 0) {
    setTimeout(() => {
      that.jsTreeMenuInit();
    }, 250);
    return;
  }
  
  if (!checkUserHasLogined(userData)) {
    return;
  }
  
  const axiosInstance = getAxiosInstance();
  axiosInstance.post(import.meta.env.VITE_API_URL + '/menu/getMemuItemAndProgList')
  .then(response => {
    if (null != response.data.value) {
      this.baseStore.menuList = response.data.value.menuList;
      this.baseStore.progList = response.data.value.programList;
      setTimeout(() => {
        that.jsTreeMenuInit();
      }, 250);
    }
  })
  .catch(e => {
    alert(e);
    this.clearUserLoginData();
  });
}

function _jsTreeMenuInit() {
  
  var treeviewMenu = document.querySelector('.app-menu');

  // Toggle Sidebar
  document.querySelector('[data-toggle="sidebar"]').addEventListener('click', function(event) {
    event.preventDefault();
    document.querySelector('.app').classList.toggle('sidenav-toggled');
  });

  // Activate sidebar treeview toggle
  var treeviewToggle = document.querySelectorAll("[data-toggle='treeview']");
  treeviewToggle.forEach(function(toggle) {
    toggle.addEventListener('click', function(event) {
      event.preventDefault();
      var parent = toggle.parentNode;
      if (!parent.classList.contains('is-expanded')) {
        var expandedToggles = treeviewMenu.querySelectorAll("[data-toggle='treeview']");
        expandedToggles.forEach(function(expandedToggle) {
          expandedToggle.parentNode.classList.remove('is-expanded');
        });
      }
      parent.classList.toggle('is-expanded');
    });
  });

  // Set initial active toggle
  var initialActiveToggle = document.querySelector("[data-toggle='treeview.'].is-expanded");
  if (initialActiveToggle) {
    initialActiveToggle.parentNode.classList.toggle('is-expanded');
  }
}

function _userLogout() {
  	Swal.fire({
  		title: '確定登出?',
  		icon: 'question',
  		iconHtml: '?',
  		confirmButtonText: 'Yes',
  		cancelButtonText: 'No',
  		showCancelButton: true,
  		showCloseButton: true
  	}).then((result) => {
  		if (result.isConfirmed) {
  			this.clearUserLoginData();
        window.location.href = '/';
  		}
  	});
}

function _clearUserLoginData() {
  userLogoutClearCookie();
  this.baseStore.clearUserData();  
}

</script>

<style>

</style>

<template>  
<ClientOnly fallback-tag="span" fallback="Loading comments...">
  <Head>
      <Title>qífū</Title>
      <Meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <Meta charset="UTF-8" />
  </Head>  
<div v-if=" 'Y' == this.baseStore.user.login " class="app sidebar-mini">
    <!-- Navbar-->
    <header class="app-header"><a class="app-header__logo" href="#" v-on:click="this.reloadPageLogoClick">qífū</a>
      <!-- Sidebar toggle button-->
      <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"><h4 style="margin-top: 10px;"><i class="bi bi-list"></i></h4></a>
      <!-- Navbar Right Menu-->
      <ul class="app-nav">
        <!-- User Menu-->
        <li class="dropdown"><a class="app-nav__item" href="#" data-bs-toggle="dropdown" aria-label="Open Profile Menu"><i class="bi bi-person fs-4"></i></a>
          <ul class="dropdown-menu settings-menu dropdown-menu-right">
            <li><a class="dropdown-item" href="#" @click="this.showUserProfile"><i class="bi bi-person-badge me-2 fs-5"></i> Profile</a></li>
            <li><a class="dropdown-item" href="#" @click="this.userLogout"><i class="bi bi-box-arrow-right me-2 fs-5"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </header>
    
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
		<ul class="app-menu">

      <!-- menu item -->
      <template v-if="null != this.baseStore && null != this.baseStore.menuList && this.baseStore.menuList.length > 0">
      <li class="treeview" v-for=" (t, idx) in this.baseStore.menuList ">
        <a class="app-menu__item" href="#" data-toggle="treeview"><i :class="'bi bi-' + t.icon"></i>&nbsp;<span class="app-menu__label">{{t.name}}</span><i class="treeview-indicator fa fa-angle-right"></i></a>
        <ul class="treeview-menu">
          <li v-for="(mdi, iidx) in t.items">
            <router-link v-bind:to=" (mdi.url.length > 0 && mdi.url.indexOf('#') == 0) ? mdi.url.substring(1, mdi.url.length) : mdi.url " class="treeview-item"><i :class="'bi bi-' + mdi.icon"></i>&nbsp;&nbsp;{{mdi.name}}</router-link>
          </li>
        </ul>
      </li>
      </template>

      
			<li><router-link to="/about" class="app-menu__item"><i class="bi bi-info-circle"></i>&nbsp;<span class="app-menu__label">About</span></router-link></li>

      <li><a class="app-menu__item" href="#" @click="this.userLogout()" ><i class="bi bi-door-open"></i>&nbsp;<span class="app-menu__label">Logout</span></a></li>
		</ul>
	</aside>
  
  <main class="app-content">      
    <div class="tab-content">
      <NuxtLayout>
        <NuxtPage/>
      </NuxtLayout>
    </div>
  </main>

</div>
<div v-if=" 'Y' != this.baseStore.user.login ">
  <NuxtPage/>
</div>
</ClientOnly>
</template>

// frontend/src/App.svelte
<script>
  import Router, { link } from "svelte-spa-router";
  import { push, pop, replace } from 'svelte-spa-router'
  import { routes } from "./routes.js";
  import { Icon } from 'sveltestrap';
  import {
  	Dropdown,
  	DropdownItem,
  	DropdownMenu,
  	DropdownToggle
  } from 'sveltestrap';
  import { onMount, beforeUpdate } from 'svelte';
  
  import LoginPage from './pages/LoginPage.svelte';

  import { _user } from './store/userStore.js';
  import { _menu, _progList } from './store/menuStore.js';

  import {
  	setRefreshAndAccessTokenCookie,
  	getRefreshTokenCookie,
  	getAccessTokenCookie,
  	userLogoutClearCookie,
  	checkUserHasLogined,
  	getAxiosInstance,
	checkHasPermission,
    checkHasRole
  }
  from "./components/BaseHelper.svelte";

  import Swal from 'sweetalert2';

  let menuData = [];
  _menu.subscribe(value => {
  	menuData = value;
  });

  let progListData = [];
  _progList.subscribe(value => {
  	progListData = value;
  });

  let userData;
  _user.subscribe(value => {
  	userData = value;
  });

  onMount(() => {

  	//loadUserLoginedFromClient();

  });

  beforeUpdate(() => {
	loadUserLoginedFromClient();
  });

  // 驗證之前是否登入 refresh token , access token            
  function loadUserLoginedFromClient() {
	var ck_user_refresh_token = getRefreshTokenCookie();
  	var ck_user_access_token = getAccessTokenCookie();
  	if (!checkUserHasLogined(userData) && (null != ck_user_refresh_token && '' != ck_user_refresh_token) && (null != ck_user_access_token && '' != ck_user_access_token)) {
  		fetch(import.meta.env.VITE_API_URL + '/auth/validLogined', {
  			method: "POST",
  			headers: {
  				"Content-Type": "application/json",
  			},
  			body: JSON.stringify({
  				accessToken: ck_user_access_token,
  				refreshToken: ck_user_refresh_token
  			}),
  			signal: AbortSignal.timeout(import.meta.env.VITE_FETCH_TIMEOUT)
  		})
  		.then(response => {
  			if (response.ok) {
  				return response.json();
  			}
  			clearUserLoginData();
  			throw new Error(response.status + ' ' + response.statusText);
  		})
  		.then((responseJson) => {
  			if (null != responseJson) {
  				_user.update((val) => {
  					return responseJson;
  				});
  				setRefreshAndAccessTokenCookie(userData.refreshToken, userData.accessToken);
  				initTreeMenu();
  			} else {
  				_user.update((val) => {
  					return {};
  				});
  			}
  		})
  		.catch((error) => {
  			clearUserLoginData();
  			console.log(error);
  		});
  	}
  }

  function initTreeMenu() {
  	if (menuData != null && menuData.length > 0) {
  		setTimeout(() => {
  			jsTreeMenuInit();
  		}, 500);
  		return;
  	}
  	if (!checkUserHasLogined(userData)) {
  		return;
  	}
  	const axiosInstance = getAxiosInstance();
  	axiosInstance.post(import.meta.env.VITE_API_URL + '/menu/getMemuItemAndProgList')
  		.then(response => {
  			if (null != response.data.value) {
  				//menuData = response.data.value;
  				_menu.update((val) => {
  					return response.data.value.menuList;
  				});
  				_progList.update((val) => {
  					return response.data.value.programList;
  				});
  				setTimeout(() => {
  					jsTreeMenuInit();
  				}, 500);
  			}
  		})
  		.catch(e => {
  			alert(e);
  			clearUserLoginData();
  		});
  }

  export function jsTreeMenuInit() {

  	var treeviewMenu = document.querySelector('.app-menu');

  	// Toggle Sidebar
  	document.querySelector('[data-toggle="sidebar"]').addEventListener('click', function(event) {
  		event.preventDefault();
  		document.querySelector('.app').classList.toggle('sidenav-toggled');
  	});

  	// Activate sidebar treeview toggle
  	var treeviewToggle = document.querySelectorAll("[data-toggle='treeview']");
  	treeviewToggle.forEach(function(toggle) {
  		toggle.addEventListener('click', function(event) {
  			event.preventDefault();
  			var parent = toggle.parentNode;
  			if (!parent.classList.contains('is-expanded')) {
  				var expandedToggles = treeviewMenu.querySelectorAll("[data-toggle='treeview']");
  				expandedToggles.forEach(function(expandedToggle) {
  					expandedToggle.parentNode.classList.remove('is-expanded');
  				});
  			}
  			parent.classList.toggle('is-expanded');
  		});
  	});

  	// Set initial active toggle
  	var initialActiveToggle = document.querySelector("[data-toggle='treeview.'].is-expanded");
  	if (initialActiveToggle) {
  		initialActiveToggle.parentNode.classList.toggle('is-expanded');
  	}

  	//Activate bootstrip tooltips
  	//jq("[data-toggle='tooltip']").tooltip();
  }


  function routeLoading(event) {
	if (event.detail.location != '/nopermission' && event.detail.location != '/about' && event.detail.location != '/') {
		if (!checkHasPermission(event.detail.location,true)) {
			replace('/nopermission');
		}
	}
	if (checkHasRole('admin') || checkHasRole('*')) {
		if (event.detail.location == '/') {
			replace('/dashboard');
		}
	}
  }

  function routeLoaded(event) {

  }

  function userLogout() {
  	Swal.fire({
  		title: '確定登出?',
  		icon: 'question',
  		iconHtml: '?',
  		confirmButtonText: 'Yes',
  		cancelButtonText: 'No',
  		showCancelButton: true,
  		showCloseButton: true
  	}).then((result) => {
  		if (result.isConfirmed) {
  			clearUserLoginData();
			replace('/');
  		}
  	});
  }

  function clearUserLoginData() {
  	userLogoutClearCookie();
  	menuData = [];
  	progListData = [];
  	_user.update((val) => {
  		return {};
  	});
  	_menu.update((val) => {
  		return [];
  	});
  	_progList.update((val) => {
  		return [];
  	});
  }
  
</script>


<style>
  @import './assets/vali.css';
  @import './assets/m.css';
</style>


{#if checkUserHasLogined(userData) }
	
    <!-- Navbar-->
    <header class="app-header"><a class="app-header__logo" href="#">qífū</a>
		<!-- Sidebar toggle button-->
		<a class="app-sidebar__toggle" href="javascript:window.location.reload();" data-toggle="sidebar" aria-label="Hide Sidebar"><h4 style="margin-top: 10px;"><Icon name="list"/></h4></a>
		<!-- Navbar Right Menu-->
		<ul class="app-nav">
			<Dropdown>
				<DropdownToggle nav class="nav-link app-nav__item"><Icon name="person-circle" /></DropdownToggle>
				<DropdownMenu>
					<DropdownItem on:click={userLogout}><Icon name="door-closed" />&nbsp;Logout</DropdownItem>
				</DropdownMenu>
			</Dropdown>
		</ul>
    </header>
    
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
		<ul class="app-menu">
			{#each menuData as md}
			<li class="treeview">
				<a class="app-menu__item" href="#" data-toggle="treeview"><Icon name="{md.icon}" />&nbsp;<span class="app-menu__label">{md.name}</span><i class="treeview-indicator fa fa-angle-right"></i></a>
				<ul class="treeview-menu">
					{#each md.items as mdi}
					<li><a class="treeview-item" href="{mdi.url}" ><Icon name="{mdi.icon}" />&nbsp;&nbsp;{mdi.name}</a></li>
					{/each}
				</ul>
			</li>
			{/each}
			
			<li><a class="app-menu__item" href="#/about" ><Icon name="info-circle" />&nbsp;<span class="app-menu__label">About</span></a></li>
			<li><a class="app-menu__item" href="javascript:false;" on:click={userLogout} ><Icon name="door-open" />&nbsp;<span class="app-menu__label">Logout</span></a></li>
		</ul>
	</aside>

    <main class="app-content">      
		<div class="tab-content">
			<Router {routes} on:routeLoading={routeLoading} on:routeLoaded={routeLoaded} />
		</div>
	</main>

{:else}
    <LoginPage initTreeMenu={initTreeMenu}/>
{/if}
