// frontend-various/frontend-v/src/views/prog001d0002/Create.vue
<script>
import { ref, watch } from 'vue';
import Swal from 'sweetalert2';
import { toast } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

import Toolbar from '@/components/Toolbar.vue';
import { PageConstants } from './config';
import { 
	getAxiosInstance, 
	invalidFeedback,
	checkInvalid,
	escapeQifuHtmlMsg
} from '../../components/BaseHelper';

let checkFields = new Object();

export default {
	components: { Toolbar },
	setup() { 
	},
	data() {
		return {
			pageProgramId : PageConstants.CreateId,
			checkFields,
			formParam : {
				progId : '',
				name : '',
				url : '',
				editModeVar : false,
				isDialogVar : false,
				editMode : 'N',
				isDialog : 'N',    
				dialogW : '0',
				dialogH : '0',
				progSystem : 'CORE',
				itemType : 'ITEM',
				fontIconClassId : 'globe2',
				icon : 'SYSTEM'
			}
		}
	},
	methods: { 
		fieldInvalidFeedback : invalidFeedback,
		fieldCheckInvalid : checkInvalid,
		btnBack : function() {
			this.$router.back();
		},
		btnSave : _btnSave,
		btnClear : function() {
			this.checkFields = new Object();
			this.formParam.progId = '';
			this.formParam.name = '';
			this.formParam.url = '';
			this.formParam.editModeVar = false;
			this.formParam.isDialogVar = false;
			this.formParam.editMode = 'N';
			this.formParam.isDialog = 'N';
			this.formParam.dialogW = '0';
			this.formParam.dialogH = '0';
			this.formParam.progSystem = 'CORE';
			this.formParam.itemType = 'ITEM';
			this.formParam.fontIconClassId = 'globe2';
			this.formParam.icon = 'SYSTEM';
		},
		refreshSwitchItemVariableFn : function() {
			if (this.formParam.editModeVar) {
				this.formParam.editMode = 'Y';
			} else {
				this.formParam.editMode = 'N';
			}
			if (this.formParam.isDialogVar) {
				this.formParam.isDialog = 'Y';
			} else {
				this.formParam.isDialog = 'N';
			}
		}
	},
	created() { 
        watch(() => this.formParam.editModeVar, (newVal, oldVal) => {
            this.refreshSwitchItemVariableFn();
        });
        watch(() => this.formParam.isDialogVar, (newVal, oldVal) => {
            this.refreshSwitchItemVariableFn();
        });
	},
	mounted() { 
	}
}

function _btnSave() {
    this.checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();      
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', this.formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
			this.checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.warning(escapeQifuHtmlMsg(response.data.message));
                return;
            }            
            toast.success(response.data.message);   
            this.btnClear();
        } else {
            toast.error('error, null');
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    });
}

</script>

<template>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<Toolbar 
			:progId="this.pageProgramId" 
        	description="程式管理，新增資料作業." 
        	marginBottom="Y"
        	refreshFlag="Y"
        	@refreshMethod="btnClear"
        	backFlag="Y"
        	@backMethod="btnBack"
        	createFlag="N"
        	@createMethod="null"
        	saveFlag="Y"
        	@saveMethod="btnSave"
    	></Toolbar>		
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="progId" class="form-label">程式編號</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('progId', checkFields) ? 'is-invalid' : ' ')" id="progId" placeholder="輸入程式編號" v-model="this.formParam.progId">
		<div v-if="fieldCheckInvalid('progId', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('progId', checkFields) }}</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="name" class="form-label">程式名稱</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('name', checkFields) ? 'is-invalid' : ' ')" id="name" placeholder="輸入程式名稱" v-model="this.formParam.name">
		<div v-if="fieldCheckInvalid('name', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('name', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
		<label for="url" class="form-label">Url</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('url', checkFields) ? 'is-invalid' : ' ')" id="url" placeholder="輸入Url" v-model="this.formParam.url">
		<div v-if="fieldCheckInvalid('url', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('url', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<div class="form-check form-switch">
			<input class="form-check-input" type="checkbox" role="switch" id="editMode" v-model="this.formParam.editModeVar">
			<label class="form-check-label" for="editMode">編輯頁</label>
		</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<div class="form-check form-switch">
			<input class="form-check-input" type="checkbox" role="switch" id="isDialog" v-model="this.formParam.isDialogVar">
			<label class="form-check-label" for="isDialog">Dialog模式</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="dialogW" class="form-label">Dialog寬</label>
		<input type="number" v-bind:class="'form-control ' + ( fieldCheckInvalid('dialogW', checkFields) ? 'is-invalid' : ' ')" id="dialogW" v-model="this.formParam.dialogW">
		<div v-if="fieldCheckInvalid('dialogW', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('dialogW', checkFields) }}</div>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="dialogH" class="form-label">Dialog高</label>
		<input type="number" v-bind:class="'form-control ' + ( fieldCheckInvalid('dialogH', checkFields) ? 'is-invalid' : ' ')" id="dialogH" v-model="this.formParam.dialogH">
		<div v-if="fieldCheckInvalid('dialogH', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('dialogH', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="dialogH" class="form-label">類別</label>
		<select class="form-select" aria-label="請選取類別" v-model="this.formParam.itemType">
			<option value="ITEM">ITEM-頁面</option>
			<option value="FOLDER">FOLDER-目錄</option>
		</select>
	</div>
	<div class="col-xs-6 col-md-6 col-lg-6">
		<label for="fontIconClassId" class="form-label">Icon class</label>
		<input type="text" v-bind:class="'form-control ' + ( fieldCheckInvalid('fontIconClassId', checkFields) ? 'is-invalid' : ' ')" id="fontIconClassId" placeholder="Icon class" v-model="this.formParam.fontIconClassId">
		<div v-if="fieldCheckInvalid('fontIconClassId', checkFields)" class="invalid-feedback d-block">{{ fieldInvalidFeedback('fontIconClassId', checkFields) }}</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-md-12 col-lg-12">
    	<button type="button" class="btn btn-primary" v-on:click="btnSave"><i class="'bi bi-save"></i>&nbsp;儲存</button>
    	&nbsp;
    	<button type="button" class="btn btn-primary" v-on:click="btnClear"><i class="'bi bi-eraser"></i>&nbsp;清除</button>		
	</div>
</div>
</template>

// frontend-various/frontend-k/src/routes/prog001d0002/create/+page.svelte
<script>
import { onMount, onDestroy } from 'svelte';    
import { goto } from '$app/navigation';
import { 
    FormGroup, Input, Label, Button, Icon
} from 'sveltestrap';
import { toast, SvelteToast } from '@zerodevx/svelte-toast';
import Swal from 'sweetalert2';
import { 
    getProgItem, getAxiosInstance, 
    getToastDefaultTheme, getToastErrorTheme, getToastWarningTheme, getToastSuccessTheme, getUrlNoStartSign,
    invalidFeedback, checkInvalid
} from "../../../components/BaseHelper.svelte";
import Toolbar from "../../../components/Toolbar.svelte";
import { PageConstants } from '../config';

let toolbarParam = {
    id          : PageConstants.CreateId,
    description : '程式管理，新增資料作業.',
    methods     : {
        "back"      :   function() {
            goto( getUrlNoStartSign(getProgItem(PageConstants.QueryId).url) );
        }
        ,
        "refresh"   :   function() {
            btnClear();
        }
        ,
        "save"      :   function() {
            btnSave();
        } 
    }
}

var formParam = {
    'progId'            :   '',
    'name'              :   '',
    'url'               :   '',
    'editModeVar'       :   false,
    'isDialogVar'       :   false,
    'editMode'          :   'N',
    'isDialog'          :   'N',    
    'dialogW'           :   '0',
    'dialogH'           :   '0',
    'progSystem'        :   'CORE',
    'itemType'          :   'ITEM',
    'fontIconClassId'   :   'globe2',
    'icon'              :   'SYSTEM'
}

var checkFields = new Object();

onMount(()=>{

});

onDestroy(()=>{
	toast.pop(0);
});

function btnSave() {
    checkFields = new Object();
    Swal.fire({title: "Loading...", html: "請等待", showConfirmButton: false, allowOutsideClick: false});
    Swal.showLoading();      
    let axiosInstance = getAxiosInstance();
    axiosInstance.post(import.meta.env.VITE_API_URL + PageConstants.eventNamespace + '/save', formParam)
    .then(response => {
        Swal.hideLoading();
        Swal.close();
        if (null != response.data) {
            checkFields = response.data.checkFields;
            if (import.meta.env.VITE_SUCCESS_FLAG != response.data.success) {
                toast.push(response.data.message, getToastWarningTheme());
                return;
            }            
            toast.push(response.data.message, getToastSuccessTheme());   
            btnClear();
        } else {
            toast.push('error, null', getToastErrorTheme());
        }
    })
    .catch(e => {
        Swal.hideLoading();
        Swal.close();        
        alert(e);
    }); 
}

function btnClear() {
    checkFields = new Object();
    formParam.progId = '';
    formParam.name = '';
    formParam.url = '';
    formParam.editModeVar = false;
    formParam.isDialogVar = false;
    formParam.editMode = 'N';
    formParam.isDialog = 'N';
    formParam.dialogW = '0';
    formParam.dialogH = '0';
    formParam.progSystem = 'CORE';
    formParam.itemType = 'ITEM';
    formParam.fontIconClassId = 'globe2';
    formParam.icon = 'SYSTEM';
}

$ : {
    if (formParam.editModeVar) {
        formParam.editMode = 'Y';
    } else {
        formParam.editMode = 'N';
    }

    if (formParam.isDialogVar) {
        formParam.isDialog = 'Y';
    } else {
        formParam.isDialog = 'N';
    }
}

</script>

<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Toolbar args={toolbarParam}></Toolbar>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="progId">程式編號</Label>
            <Input type="text" id="progId" placeholder="輸入程式編號" feedback={invalidFeedback('progId', checkFields)} invalid={checkInvalid('progId', checkFields)} bind:value={formParam.progId} />
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="name">程式名稱</Label>
            <Input type="text" id="name" placeholder="輸入名稱" feedback={invalidFeedback('name', checkFields)} invalid={checkInvalid('name', checkFields)} bind:value={formParam.name} />
        </FormGroup> 
    </div>    
</div>
<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <FormGroup>
            <Label for="url">Url</Label>
            <Input type="text" id="url" placeholder="輸入Url" feedback={invalidFeedback('url', checkFields)} invalid={checkInvalid('url', checkFields)} bind:value={formParam.url} />            
        </FormGroup>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Input id="editMode" type="switch" label="編輯頁" bind:checked={formParam.editModeVar} />            
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Input id="isDialog" type="switch" label="Dialog模式" bind:checked={formParam.isDialogVar} />
        </FormGroup> 
    </div>    
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="dialogW">Dialog寬</Label>
            <Input type="number" id="dialogW" placeholder="Dialog width" feedback={invalidFeedback('dialogW', checkFields)} invalid={checkInvalid('dialogW', checkFields)} bind:value={formParam.dialogW} />
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="dialogH">Dialog高</Label>
            <Input type="number" id="dialogH" placeholder="Dialog height" feedback={invalidFeedback('dialogH', checkFields)} invalid={checkInvalid('dialogH', checkFields)} bind:value={formParam.dialogH} />
        </FormGroup> 
    </div>    
</div>
<div class="row">
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <FormGroup floating label="類別">
                <Input type="select" placeholder="請選取類別" bind:value={formParam.itemType}>
                    <option value="ITEM">ITEM-頁面</option>
                    <option value="FOLDER">FOLDER-目錄</option>
                </Input>
              </FormGroup>
        </FormGroup>         
    </div>
    <div class="col-xs-6 col-md-6 col-lg-6">
        <FormGroup>
            <Label for="fontIconClassId">Icon class</Label>
            <Input type="text" id="fontIconClassId" placeholder="Icon class" feedback={invalidFeedback('fontIconClassId', checkFields)} invalid={checkInvalid('fontIconClassId', checkFields)} bind:value={formParam.fontIconClassId} />
        </FormGroup> 
    </div>    
</div>

<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <Button color="primary" on:click={btnSave}><Icon name="save"/>&nbsp;儲存</Button>
        &nbsp;
        <Button color="primary" on:click={btnClear}><Icon name="eraser"/>&nbsp;清除</Button>
    </div>
</div>    

<SvelteToast></SvelteToast>
